/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.Scenes {
    export class GameUI extends Laya.View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Scenes/Game");
        }
    }
    REG("ui.Scenes.GameUI",GameUI);
    export class StartUI extends Laya.View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Scenes/Start");
        }
    }
    REG("ui.Scenes.StartUI",StartUI);
}