/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GamePage from "./script/Pages/GamePage"
import LoadingPage from "./script/Pages/LoadingPage"
import MoneyInfo from "./script/UI/Compoments/MoneyInfo"
import Home from "./script/UI/Home"
import Loading from "./script/UI/Loading"
import Playing from "./script/UI/Playing"
import Relife from "./script/UI/Relife"
import RankItem from "./script/UI/Compoments/RankItem"
import Result from "./script/UI/Result"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="center";
    static startScene:any="Scenes/Start.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/Pages/GamePage.ts",GamePage);
        reg("script/Pages/LoadingPage.ts",LoadingPage);
        reg("script/UI/Compoments/MoneyInfo.ts",MoneyInfo);
        reg("script/UI/Home.ts",Home);
        reg("script/UI/Loading.ts",Loading);
        reg("script/UI/Playing.ts",Playing);
        reg("script/UI/Relife.ts",Relife);
        reg("script/UI/Compoments/RankItem.ts",RankItem);
        reg("script/UI/Result.ts",Result);
    }
}
GameConfig.init();